In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.options.display.max_columns=100 #(设定能显示的列数)

In [16]:
data = pd.read_csv('/Users/paxton615/database/2018-2019_886_school_information.csv')
kent = data

In [17]:
kent.head()

,URN,LANAME,LA,ESTAB,LAESTAB,SCHNAME,STREET,LOCALITY,ADDRESS3,TOWN,...,MINORGROUP,SCHOOLTYPE,ISPRIMARY,ISSECONDARY,ISPOST16,AGELOW,AGEHIGH,GENDER,RELCHAR,ADMPOL
0,118245,Kent,886,2062,8862062,Darenth Community Primary School,Green Street Green Road,Darenth,NaN,Dartford,...,Maintained school,Community school,1,0,0,5,11,Mixed,Does not apply,Not applicable
1,118246,Kent,886,2066,8862066,Maypole Primary School,Franklin Road,NaN,NaN,Dartford,...,Maintained school,Community school,1,0,0,4,11,Mixed,Does not apply,Not applicable
2,118254,Kent,886,2088,8862088,Crockenhill Primary School,The Green,Crockenhill,NaN,NaN,...,Maintained school,Community school,1,0,0,4,11,Mixed,Does not apply,Not applicable
3,118255,Kent,886,2089,8862089,The Anthony Roper Primary School,High Street,Eynsford,NaN,Dartford,...,Maintained school,Foundation school,1,0,0,4,11,Mixed,None,Not applicable
4,118257,Kent,886,2094,8862094,Cobham Primary School,The Street,Cobham,NaN,Gravesend,...,Maintained school,Community school,1,0,0,4,11,Mixed,Does not apply,Not applicable

In [18]:
kent['TOWN'].unique()

array(['Dartford', nan, 'Gravesend', 'Rochester', 'Tonbridge',
       'Sevenoaks', 'Edenbridge', 'Tunbridge Wells', 'Cranbrook',
       'Maidstone', 'Headcorn', 'West Malling', 'Snodland', 'Faversham',
       'Sittingbourne', 'Queenborough', 'Sheerness', 'Canterbury',
       'Herne Bay', 'Whitstable', 'Ashford', 'Folkestone', 'Dover',
       'Deal', 'Broadstairs', 'Westgate-on-Sea', 'Ramsgate', 'Riverhead',
       'Aylesford', 'Hythe', 'Chatham', 'Swanley', 'Sandwich', 'Margate',
       'Swanley Village', 'Longfield', 'Westerham', 'Gillingham',
       'CANTERBURY', 'Romney Marsh', 'Birchington', 'Westgate on Sea',
       'Tenterden', 'New Romney', 'DEAL', 'Otford', 'CRANBROOK', 'Kent',
       'Swanscombe', 'Paddock Wood', 'Minster-on-Sea', 'Wilmington',
       'Bexley', 'Temple Ewell', 'East Malling', 'Wye', 'Hadlow',
       'Ebbsfleet', 'Greenhithe', 'Northfleet', 'Stone', 'Doddington'],
      dtype=object)

In [19]:
data = pd.read_csv('/Users/paxton615/database/2018-2019_england_school_information.csv')

In [20]:
england = data

In [56]:

england

,URN,LANAME,LA,ESTAB,LAESTAB,SCHNAME,STREET,LOCALITY,ADDRESS3,TOWN,POSTCODE,SCHSTATUS,OPENDATE,CLOSEDATE,MINORGROUP,SCHOOLTYPE,ISPRIMARY,ISSECONDARY,ISPOST16,AGELOW,AGEHIGH,GENDER,RELCHAR,ADMPOL
0,100000,City of London,201,3614,2013614,The Aldgate School,St James's Passage,Duke's Place,NaN,London,EC3A 5DE,Open,NaN,NaN,Maintained school,Voluntary aided school,1,0,0,3.0,11.0,Mixed,Church of England,Not applicable
1,100001,City of London,201,6005,2016005,City of London School for Girls,St Giles' Terrace,Barbican,NaN,London,EC2Y 8BB,Open,NaN,NaN,Independent school,Other independent school,1,1,1,7.0,18.0,Girls,None,Not applicable
2,100002,City of London,201,6006,2016006,St Paul's Cathedral School,2 New Change,NaN,NaN,London,EC4M 9AD,Open,NaN,NaN,Independent school,Other independent school,1,1,0,4.0,13.0,Mixed,Church of England,Not applicable
3,100003,City of London,201,6007,2016007,City of London School,107 Queen Victoria Street,NaN,NaN,London,EC4V 3AL,Open,NaN,NaN,Independent school,Other independent school,1,1,1,10.0,18.0,Boys,None,Not applicable
4,100008,Camden,202,2019,2022019,Argyle Primary School,Tonbridge Street,NaN,NaN,London,WC1H 9EG,Open,NaN,NaN,Maintained school,Community school,1,0,0,3.0,11.0,Mixed,Does not apply,Not applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25550,148538,Derby,831,4011,8314011,Alvaston Moor Academy,Brackens Lane,NaN,NaN,Derby,DE24 0AN,Open,01-02-2021,NaN,Academy,Academy sponsor led,0,1,1,11.0,19.0,Mixed,None,NaN
25551,148545,Bradford,380,4092,3804092,Trinity Academy Bradford,Deanstones Lane,NaN,NaN,Bradford,BD13 2AS,Open,01-02-2021,NaN,Academy,Academy sponsor led,0,1,0,11.0,16.0,Mixed,None,NaN
25552,148547,Rotherham,372,4009,3724009,Thrybergh Academy and Sports College,Arran Hill,NaN,"Arran Hill, Thrybergh",Rotherham,S65 4BJ,Open,01-02-2021,NaN,Academy,Academy converter,1,1,0,3.0,16.0,Mixed,None,NaN
25553,148549,Leicestershire,855,4042,8554042,Ashby School,Nottingham Road,NaN,NaN,Ashby-De-La-Zouch,LE65 1DT,Open,01-03-2021,NaN,Academy,Academy converter,0,1,1,14.0,18.0,Mixed,None,NaN
25554,148550,Somerset,933,2053,9332053,Othery Village School,NaN,Othery,NaN,Bridgwater,TA7 0PX,Open,01-02-2021,NaN,Academy,Academy converter,1,0,0,2.0,11.0,Mixed,None,NaN

In [57]:
england.ADMPOL.unique()

array(['Not applicable', 'Non-selective', 'Selective', nan], dtype=object)

In [23]:
england[england['TOWN']=='London'].count()

URN            1840
LANAME         1840
LA             1840
ESTAB          1840
LAESTAB        1840
SCHNAME        1840
STREET         1839
LOCALITY       1143
ADDRESS3        199
TOWN           1840
POSTCODE       1839
SCHSTATUS      1840
OPENDATE         61
CLOSEDATE        73
MINORGROUP     1840
SCHOOLTYPE     1840
ISPRIMARY      1840
ISSECONDARY    1840
ISPOST16       1840
AGELOW         1836
AGEHIGH        1836
GENDER         1839
RELCHAR        1811
ADMPOL         1778
dtype: int64

In [27]:
england.TOWN.nunique()

1556

In [30]:
town = pd.DataFrame(england.groupby('TOWN')['LA'].count())

In [33]:
town[town['LA'] >= 20]

             LA
TOWN
Abingdon     38
Accrington   34
Alfreton     32
Altrincham   32
Amersham     21
...         ...
Workington   22
Worksop      29
Worthing     39
Yeovil       32
York        151

[325 rows x 1 columns]

In [34]:
town[town['LA'] >= 50]

                LA
TOWN
Ashford         61
Aylesbury       63
Banbury         50
Barnsley        84
Basingstoke     57
...            ...
Wigan           98
Wirral          80
Wolverhampton  128
Worcester       65
York           151

[104 rows x 1 columns]

In [35]:
town[town['LA'] >= 100]

                       LA
TOWN
Bedford               106
Birmingham            500
Bolton                145
Bradford              181
Bristol               332
Cambridge             127
Colchester            107
Coventry              149
Derby                 169
Doncaster             161
Hull                  114
Leeds                 265
Leicester             238
Lincoln               104
Liverpool             274
London               1840
Manchester            419
Milton Keynes         122
Newcastle-upon-Tyne   144
Northampton           140
Norwich               199
Nottingham            310
Oldham                111
Peterborough          126
Plymouth              114
Preston               171
Reading               161
Rotherham             105
Sheffield             246
Southampton           154
Stockport             109
Stoke-on-Trent        188
Swindon               118
Warrington            105
Wolverhampton         128
York                  151

In [36]:
england[england['TOWN'] == 'Guildford']

,URN,LANAME,LA,ESTAB,LAESTAB,SCHNAME,STREET,LOCALITY,ADDRESS3,TOWN,...,MINORGROUP,SCHOOLTYPE,ISPRIMARY,ISSECONDARY,ISPOST16,AGELOW,AGEHIGH,GENDER,RELCHAR,ADMPOL
12534,124975,Surrey,936,2133,9362133,Stoughton Infant School,Stoughton Road,NaN,NaN,Guildford,...,Maintained school,Community school,1,0,0,3.0,7.0,Mixed,Does not apply,Not applicable
12544,124992,Surrey,936,2229,9362229,Shalford Infant School,Station Row,Shalford,NaN,Guildford,...,Maintained school,Community school,1,0,0,5.0,7.0,Mixed,Does not apply,Not applicable
12551,125004,Surrey,936,2286,9362286,Wood Street Infant School,Wood Street,NaN,NaN,Guildford,...,Maintained school,Community school,1,0,0,4.0,7.0,Mixed,Does not apply,Not applicable
12554,125009,Surrey,936,5220,9365220,Bushy Hill Junior School,Sheeplands Avenue,Merrow,NaN,Guildford,...,Maintained school,Foundation school,1,0,0,7.0,11.0,Mixed,None,Not applicable
12562,125025,Surrey,936,2349,9362349,Worplesdon Primary School,Envis Way,Worplesdon,NaN,Guildford,...,Maintained school,Community school,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
12584,125067,Surrey,936,2448,9362448,Onslow Infant School,Powell Close,Onslow Village,NaN,Guildford,...,Maintained school,Community school,1,0,0,5.0,7.0,Mixed,Does not apply,Not applicable
12592,125079,Surrey,936,2484,9362484,Tillingbourne Junior School,New Road,Chilworth,NaN,Guildford,...,Maintained school,Community school,1,0,0,7.0,11.0,Mixed,Does not apply,Not applicable
12632,125160,Surrey,936,3061,9363061,Merrow CofE Controlled Infant School,Kingfisher Drive,Merrow,NaN,Guildford,...,Maintained school,Voluntary controlled school,1,0,0,4.0,7.0,Mixed,Church of England,Not applicable
12636,125167,Surrey,936,3317,9363317,Chilworth CofE (Aided) Infant School,Dorking Road,Chilworth,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,4.0,7.0,Mixed,Church of England,Not applicable
12653,125189,Surrey,936,3357,9363357,St Nicolas CofE Aided Infant School,Portsmouth Road,NaN,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,5.0,7.0,Mixed,Church of England,Not applicable
12659,125195,Surrey,936,3381,9363381,Puttenham CofE Infant School,School Lane,Puttenham,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,5.0,7.0,Mixed,Church of England,Not applicable
12663,125199,Surrey,936,3408,9363408,Clandon CofE Aided Primary School,The Street,West Clandon,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,5.0,10.0,Mixed,Church of England,Not applicable
12666,125202,Surrey,936,3417,9363417,Wonersh and Shamley Green CofE Aided Primary S...,Guildford Road,Shamley Green,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,4.0,11.0,Mixed,Church of England,Not applicable
12690,125243,Surrey,936,3925,9363925,Bramley CofE Aided Infant School and Nursery,Birtley Road,Bramley,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,2.0,7.0,Mixed,Church of England,Not applicable
12692,125246,Surrey,936,3928,9363928,Shere CofE Aided Infant School,Gomshall Lane,Shere,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,2.0,7.0,Mixed,Church of England,Non-selective
12698,125276,Surrey,936,4619,9364619,St Peter's Catholic School,Horseshoe Lane East,Merrow,NaN,Guildford,...,Maintained school,Voluntary aided school,0,1,1,11.0,18.0,Mixed,Roman Catholic,Non-selective
12703,125288,Surrey,936,5206,9365206,"Holy Trinity, Guildford, CofE Aided Junior School",Addison Road,NaN,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,7.0,11.0,Mixed,Church of England,Not applicable
12705,125291,Surrey,936,5209,9365209,St Thomas of Canterbury Catholic Primary School,Horseshoe Lane West,Merrow,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,4.0,11.0,Mixed,Roman Catholic,Not applicable
12710,125299,Surrey,936,5217,9365217,Burpham Foundation Primary School,Burpham Lane,Burpham,NaN,Guildford,...,Maintained school,Foundation school,1,0,0,4.0,11.0,Mixed,None,Not applicable
12716,125320,Surrey,936,6004,9366004,St Catherine's School,Station Road,Bramley,NaN,Guildford,...,Independent school,Other independent school,1,1,1,4.0,18.0,Girls,Church of England,Not applicable
12733,125342,Surrey,936,6046,9366046,Guildford High School,London Road,NaN,NaN,Guildford,...,Independent school,Other independent school,1,1,1,4.0,19.0,Girls,Christian,Selective
12734,125343,Surrey,936,6047,9366047,Lanesborough School,Maori Road,NaN,NaN,Guildford,...,Independent school,Other independent school,1,0,0,3.0,11.0,Boys,Christian,Selective
12735,125344,Surrey,936,6049,9366049,Rydes Hill Preparatory School,Rydes Hill House,Aldershot Road,NaN,Guildford,...,Independent school,Other independent school,1,0,0,3.0,11.0,Mixed,Roman Catholic,Non-selective
12736,125345,Surrey,936,6050,9366050,Tormead School,Cranley Road,NaN,NaN,Guildford,...,Independent school,Other independent school,1,1,1,4.0,18.0,Girls,None,Not applicable
12771,125392,Surrey,936,6308,9366308,Barfield School,NaN,Runfold,NaN,Guildford,...,Independent school,Other independent school,1,1,0,2.0,13.0,Mixed,None,Non-selective
12772,125393,Surrey,936,6315,9366315,Longacre School,Hullbrook Lane,Shamley Green,NaN,Guildford,...,Independent school,Other independent school,1,0,0,2.0,11.0,Mixed,None,Not applicable
12807,125452,Surrey,936,7003,9367003,Gosden House School,Horsham Road,Bramley,NaN,Guildford,...,Special school,Community special school,1,1,0,4.0,16.0,Mixed,Does not apply,Not applicable
12815,125466,Surrey,936,7035,9367035,Wey House School,Horsham Road,Bramley,NaN,Guildford,...,Special school,Community special school,1,0,0,5.0,11.0,Boys,Does not apply,Not applicable
13669,130823,Surrey,936,8002,9368002,Guildford College of Further and Higher Education,Stoke Park,NaN,NaN,Guildford,...,College,Further education,0,0,1,16.0,99.0,Mixed,Does not apply,Not applicable
13810,131112,Surrey,936,3932,9363932,St Joseph's Catholic Primary School,155 Aldershot Road,NaN,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,4.0,11.0,Mixed,Roman Catholic,Not applicable
15174,135566,Surrey,936,3944,9363944,Cranleigh Church of England Primary School,Parsonage Road,Cranleigh,NaN,Guildford,...,Maintained school,Voluntary controlled school,1,0,0,4.0,11.0,Mixed,Church of England,Not applicable
15962,136755,Surrey,936,2001,9362001,Pewley Down Infant School,Semaphore Road,NaN,NaN,Guildford,...,Maintained school,Voluntary aided school,1,0,0,4.0,7.0,Mixed,Church of England,Non-selective
16102,136906,Surrey,936,4456,9364456,George Abbot School,Woodruff Avenue,NaN,NaN,Guildford,...,Academy,Academy converter,0,1,1,11.0,18.0,Mixed,Does not apply,Non-selective
17945,139070,Surrey,936,2011,9362011,Weyfield Academy,School Close,Off Woking Road,NaN,Guildford,...,Academy,Academy sponsor led,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
18052,139193,Surrey,936,5400,9365400,Guildford County School,Farnham Road,NaN,NaN,Guildford,...,Academy,Academy converter,0,1,1,11.0,18.0,Mixed,None,Non-selective
18764,140057,Surrey,936,2374,9362374,Boxgrove Primary School,Boxgrove Lane,Merrow,NaN,Guildford,...,Academy,Academy converter,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
18889,140203,Surrey,936,6572,9366572,Peaslake Free School,Colmans Hill,Peaslake,NaN,Guildford,...,Academy,Free schools,1,0,0,3.0,7.0,Mixed,None,Not applicable
19757,141197,Surrey,936,2031,9362031,Sandfield Primary School,Stoke Road,NaN,NaN,Guildford,...,Academy,Academy sponsor led,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
19760,141200,Surrey,936,4001,9364001,Kings College Guildford,Southway,NaN,NaN,Guildford,...,Academy,Academy sponsor led,0,1,0,11.0,16.0,Mixed,None,Non-selective
19948,141446,Surrey,936,3353,9363353,Queen Eleanor's Church of England School,Queen Eleanor's Road,NaN,NaN,Guildford,...,Academy,Academy converter,1,0,0,7.0,11.0,Mixed,Church of England,Not applicable
20022,141533,Surrey,936,7042,9367042,Pond Meadow School,Larch Avenue,NaN,NaN,Guildford,...,Special school,Academy special converter,1,1,1,2.0,19.0,Mixed,Does not apply,Not applicable
20855,142490,Surrey,936,4028,9364028,"Christ's College, Guildford",Larch Avenue,NaN,NaN,Guildford,...,Academy,Academy converter,0,1,1,11.0,18.0,Mixed,Church of England,Non-selective
21609,143373,Surrey,936,2963,9362963,Guildford Grove Primary School,Southway,NaN,NaN,Guildford,...,Academy,Academy converter,1,0,0,3.0,11.0,Mixed,Does not apply,Not applicable
23260,145383,Surrey,936,7067,9367067,Grafham Grange School,Grafham,Bramley,NaN,Guildford,...,Special school,Academy special converter,1,1,1,10.0,19.0,Mixed,Does not apply,Not applicable
23400,145543,Surrey,936,2004,9362004,Wyke Primary Academy,School Lane,Normandy,NaN,Guildford,...,Academy,Academy converter,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
23797,146022,Surrey,936,2229,9362229,Shalford Infant School,Shalford Infant School,Station Row,Shalford,Guildford,...,Academy,Academy converter,1,0,0,2.0,7.0,Mixed,Does not apply,Not applicable
23800,146025,Surrey,936,5212,9365212,Northmead Junior School,Grange Road,NaN,NaN,Guildford,...,Academy,Academy converter,1,0,0,7.0,11.0,Mixed,None,Not applicable
23990,146259,Surrey,936,2133,9362133,Stoughton Infant School,Stoughton Road,NaN,NaN,Guildford,...,Academy,Academy converter,1,0,0,3.0,7.0,Mixed,Does not apply,Not applicable
24053,146338,Surrey,936,6015,9366015,Arun Court School,Arun Court,14 High Street,Bramley,Guildford,...,Special school,Other independent special school,0,1,1,11.0,17.0,Mixed,None,Not applicable
24873,147430,Surrey,936,4619,9364619,St Peter's Catholic School,Horseshoe Lane East,Merrow,NaN,Guildford,...,Academy,Academy converter,0,1,1,11.0,18.0,Mixed,Roman Catholic,Non-selective
24874,147431,Surrey,936,5209,9365209,St Thomas of Canterbury Catholic Primary School,Horseshoe Lane West,Merrow,NaN,Guildford,...,Academy,Academy converter,1,0,0,4.0,11.0,Mixed,Roman Catholic,Not applicable
25122,147789,Surrey,936,6043,9366043,Elysian Animal Assisted Therapy and Learning,"Westland Farm, Lordshill Common",Shamley Green,NaN,Guildford,...,Independent school,Other independent school,0,1,0,11.0,16.0,Mixed,NaN,NaN
25246,147943,Surrey,936,7004,9367004,Bramley Oak Academy,Horsham Road,Bramley,NaN,Guildford,...,Special school,Academy special sponsor led,1,0,0,5.0,11.0,Boys,Does not apply,Not applicable

In [ ]:
Oxfordshire

In [41]:
england[england['LANAME'] == 'Kent']

,URN,LANAME,LA,ESTAB,LAESTAB,SCHNAME,STREET,LOCALITY,ADDRESS3,TOWN,POSTCODE,SCHSTATUS,OPENDATE,CLOSEDATE,MINORGROUP,SCHOOLTYPE,ISPRIMARY,ISSECONDARY,ISPOST16,AGELOW,AGEHIGH,GENDER,RELCHAR,ADMPOL
9251,118245,Kent,886,2062,8862062,Darenth Community Primary School,Green Street Green Road,Darenth,NaN,Dartford,DA2 8DH,Closed,NaN,31-01-2019,Maintained school,Community school,1,0,0,5.0,11.0,Mixed,Does not apply,Not applicable
9252,118246,Kent,886,2066,8862066,Maypole Primary School,Franklin Road,NaN,NaN,Dartford,DA2 7UZ,Open,NaN,NaN,Maintained school,Community school,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
9253,118254,Kent,886,2088,8862088,Crockenhill Primary School,The Green,Crockenhill,NaN,NaN,BR8 8JG,Open,NaN,NaN,Maintained school,Community school,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
9254,118255,Kent,886,2089,8862089,The Anthony Roper Primary School,High Street,Eynsford,NaN,Dartford,DA4 0AA,Open,NaN,NaN,Maintained school,Foundation school,1,0,0,4.0,11.0,Mixed,None,Not applicable
9255,118257,Kent,886,2094,8862094,Cobham Primary School,The Street,Cobham,NaN,Gravesend,DA12 3BN,Open,NaN,NaN,Maintained school,Community school,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25345,148116,Kent,886,2183,8862183,Marden Primary Academy,Goudhurst Road,Marden,NaN,Tonbridge,TN12 9JX,Open,01-09-2020,NaN,Academy,Academy converter,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable
25347,148118,Kent,886,3106,8863106,Eastchurch Church of England Primary School,Warden Road,Eastchurch,NaN,Sheerness,ME12 4EJ,Open,01-09-2020,NaN,Academy,Academy converter,1,0,0,3.0,11.0,Mixed,Church of England,Not applicable
25414,148217,Kent,886,5202,8865202,Holy Trinity Church of England Primary School,Trinity Road,NaN,NaN,Gravesend,DA12 1LU,Open,01-11-2020,NaN,Academy,Academy converter,1,0,0,3.0,11.0,Mixed,Church of England,Not applicable
25478,148308,Kent,886,3173,8863173,Kingsdown and Ringwould Church of England Prim...,Glen Road,Kingsdown,NaN,Deal,CT14 8DD,Open,01-01-2021,NaN,Academy,Academy converter,1,0,0,4.0,11.0,Mixed,Church of England,Not applicable
25516,148370,Kent,886,2327,8862327,Worth Primary School,The Street,NaN,NaN,Deal,CT14 0DF,Open,01-03-2021,NaN,Academy,Academy converter,1,0,0,4.0,11.0,Mixed,Does not apply,Not applicable

In [43]:
Oxfordshire_secondary_schools = pd.DataFrame(england[england['LANAME'] == 'Oxfordshire'].groupby('TOWN').count().POSTCODE)

In [55]:
Oxfordshire_secondary_schools[Oxfordshire_secondary_schools['POSTCODE']>=10].sort_values(by='POSTCODE', ascending=False)

                  POSTCODE
TOWN
Oxford                  94
Banbury                 40
Abingdon                38
Witney                  29
Bicester                24
Didcot                  19
Wallingford             15
Wantage                 13
Chipping Norton         12
Henley-on-Thames        11
Kidlington              11

In [52]:
kent_secondary_schools = pd.DataFrame(england[england['LANAME'] == 'Kent'].groupby('TOWN').count().POSTCODE)

In [54]:
kent_secondary_schools[kent_secondary_schools['POSTCODE']>=10].sort_values(by='POSTCODE', ascending=False)

                 POSTCODE
TOWN
Maidstone              65
Ashford                52
Canterbury             49
Gravesend              41
Tonbridge              41
Tunbridge Wells        37
Sevenoaks              37
Sittingbourne          36
Dartford               32
Dover                  32
Folkestone             27
Deal                   22
Ramsgate               21
Cranbrook              17
Faversham              16
Broadstairs            14
West Malling           11
Margate                11
Sheerness              10
Herne Bay              10

In [59]:
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.datasets import register_url

try:
    register_url("https://echarts-maps.github.io/echarts-countries-js/")
except Exception:
    import ssl

    ssl._create_default_https_context = ssl._create_unverified_context
    register_url("https://echarts-maps.github.io/echarts-countries-js/")

geo = (
    Geo()
    .add_schema(maptype="英国")
    .set_global_opts(title_opts=opts.TitleOpts(title="英国"))
    .render("geo_chart_countries_js.html")
)

In [6]:
from IPython.display import Image
from IPython.display import IFrame

In [16]:
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.faker import Faker

c = (
    Geo()
    .add_schema(maptype="英国")
    .add("geo", [[['london',100],['york',200]]])
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(is_piecewise=True),
        title_opts=opts.TitleOpts(title="Geo-VisualMap（分段型）"),
    )
    .render("geo_visualmap_piecewise.html")
)
IFrame(src='./funnel_chart.html', width=1000, height=600)

TypeError: unhashable type: 'list'

In [9]:
Image(filename='/Users/paxton615/Github_Personal/Notes/Notes/UK_Schools/geo_visualmap_piecewise.html')

ValueError: Cannot embed the 'html' image format

In [14]:
[list(z) for z in zip(Faker.provinces, Faker.values())]

[['广东', 134],
 ['北京', 96],
 ['上海', 44],
 ['江西', 144],
 ['湖南', 134],
 ['浙江', 112],
 ['江苏', 115]]