In [1]:
import pandas as pd

In [5]:
from pandas_datareader import data as web

In [4]:
import pandas_datareader as pdr
pdr.get_data_fred('GS10')

            GS10
DATE
2016-03-01  1.89
2016-04-01  1.81
2016-05-01  1.81
2016-06-01  1.64
2016-07-01  1.50
2016-08-01  1.56
2016-09-01  1.63
2016-10-01  1.76
2016-11-01  2.14
2016-12-01  2.49
2017-01-01  2.43
2017-02-01  2.42
2017-03-01  2.48
2017-04-01  2.30
2017-05-01  2.30
2017-06-01  2.19
2017-07-01  2.32
2017-08-01  2.21
2017-09-01  2.20
2017-10-01  2.36
2017-11-01  2.35
2017-12-01  2.40
2018-01-01  2.58
2018-02-01  2.86
2018-03-01  2.84
2018-04-01  2.87
2018-05-01  2.98
2018-06-01  2.91
2018-07-01  2.89
2018-08-01  2.89
2018-09-01  3.00
2018-10-01  3.15
2018-11-01  3.12
2018-12-01  2.83
2019-01-01  2.71
2019-02-01  2.68
2019-03-01  2.57
2019-04-01  2.53
2019-05-01  2.40
2019-06-01  2.07
2019-07-01  2.06
2019-08-01  1.63
2019-09-01  1.70
2019-10-01  1.71
2019-11-01  1.81
2019-12-01  1.86
2020-01-01  1.76
2020-02-01  1.50
2020-03-01  0.87
2020-04-01  0.66
2020-05-01  0.67
2020-06-01  0.73
2020-07-01  0.62
2020-08-01  0.65
2020-09-01  0.68
2020-10-01  0.79
2020-11-01  0.87
2020-12-01  0.93
2021-01-01  1.08